### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

a = np.random.randint(1, 100, 15)
print(a)
print()
np.sort(a)

# Reason for using .sort() and sorted function is, sorted() func returns a list

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]



array([ 6, 24, 25, 26, 32, 48, 54, 60, 64, 67, 67, 75, 76, 86, 95])

In [2]:
np.sort(a)[::-1]
# DESC

array([95, 86, 76, 75, 67, 67, 64, 60, 54, 48, 32, 26, 25, 24,  6])

In [3]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
print(b)

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]


In [4]:
print(np.sort(b, axis=1))
# 1 is for rows

[[19 22 44 96]
 [ 8 14 36 98]
 [ 4 31 36 75]
 [21 33 41 89]
 [ 4  7 13 89]
 [47 48 61 90]]


In [5]:
print(np.sort(b, axis=0))
# 0 is for column wise

[[ 4 33 13  4]
 [14 48 31  7]
 [19 75 36  8]
 [21 89 44 22]
 [36 96 61 41]
 [90 98 89 47]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
print(a)
print()
print(np.append(a, 200))
print()
print(np.append(a, [100, 400]))

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]

[ 48  67   6  26  60  24  75  54  76  67  32  64  86  25  95 200]

[ 48  67   6  26  60  24  75  54  76  67  32  64  86  25  95 100 400]


In [7]:
print(b)
print()
print(np.append(b, np.ones((b.shape[0], 1)), axis=1))
print()
print(np.append(b, np.random.random((b.shape[0], 1)), axis=1))

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]

[[19. 96. 44. 22.  1.]
 [14. 98. 36.  8.  1.]
 [36. 75. 31.  4.  1.]
 [21. 33. 89. 41.  1.]
 [ 4. 89. 13.  7.  1.]
 [90. 48. 61. 47.  1.]]

[[1.90000000e+01 9.60000000e+01 4.40000000e+01 2.20000000e+01
  1.23918518e-01]
 [1.40000000e+01 9.80000000e+01 3.60000000e+01 8.00000000e+00
  9.65827294e-01]
 [3.60000000e+01 7.50000000e+01 3.10000000e+01 4.00000000e+00
  8.17649213e-03]
 [2.10000000e+01 3.30000000e+01 8.90000000e+01 4.10000000e+01
  7.63708637e-01]
 [4.00000000e+00 8.90000000e+01 1.30000000e+01 7.00000000e+00
  8.59795575e-01]
 [9.00000000e+01 4.80000000e+01 6.10000000e+01 4.70000000e+01
  4.45155079e-01]]


### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [9]:
# we provide a tuple in it
print(np.concatenate((c, d), axis=0))
print()
print(np.concatenate((c, d), axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [10]:
e = np.array([1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 7, 8, 8])
print(np.unique(e))

[1 2 3 4 5 6 7 8]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [11]:
print(a)
print(a.shape)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]
(15,)


In [12]:
print(np.expand_dims(a, axis=0))
print(np.expand_dims(a, axis=0).shape)

[[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]]
(1, 15)


In [13]:
print(np.expand_dims(a, axis=1))

[[48]
 [67]
 [ 6]
 [26]
 [60]
 [24]
 [75]
 [54]
 [76]
 [67]
 [32]
 [64]
 [86]
 [25]
 [95]]


### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [14]:
print(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


In [15]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 1,  4,  6,  7,  8,  9, 11, 12, 14], dtype=int64),)

In [16]:
# replace all values > 50 with 0
# np.where(condition, if true what VALUE, if false what VALUE)
np.where(a > 50, 0, a)

array([48,  0,  6, 26,  0, 24,  0,  0,  0,  0, 32,  0,  0, 25,  0])

In [17]:
# Convert all even numbers with 1
np.where(a % 2 == 0, 1, a)

array([ 1, 67,  1,  1,  1,  1, 75,  1,  1, 67,  1,  1,  1, 25, 95])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [18]:
print(a)
np.argmax(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


14

In [19]:
print(b)
np.argmax(b, axis=1)
# row wise

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]


array([1, 1, 1, 2, 1, 0], dtype=int64)

In [20]:
np.argmax(b, axis=0)

array([5, 1, 3, 5], dtype=int64)

In [21]:
# np.argmin()
print(a)
np.argmin(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


2

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [22]:
print(a)
print(np.cumsum(a))

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]
[ 48 115 121 147 207 231 306 360 436 503 535 599 685 710 805]


In [23]:
print(b)
print(np.cumsum(b))

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]
[  19  115  159  181  195  293  329  337  373  448  479  483  504  537
  626  667  671  760  773  780  870  918  979 1026]


In [24]:
print(np.cumsum(b, axis=0))

[[ 19  96  44  22]
 [ 33 194  80  30]
 [ 69 269 111  34]
 [ 90 302 200  75]
 [ 94 391 213  82]
 [184 439 274 129]]


In [25]:
print(np.cumsum(b, axis=1))

[[ 19 115 159 181]
 [ 14 112 148 156]
 [ 36 111 142 146]
 [ 21  54 143 184]
 [  4  93 106 113]
 [ 90 138 199 246]]


In [26]:
# np.cumprod
print(a)
np.cumprod(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


array([         48,        3216,       19296,      501696,    30101760,
         722442240, -1651406848,  1018343424,    84688896,  1379188736,
        1184366592, -1509949440, -1006632960,   603979776,  1543503872])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [27]:
print(a)
print(np.percentile(a, 0))
print(np.percentile(a, 50))
print(np.percentile(a, 100))

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]
6.0
60.0
95.0


In [28]:
np.median(a)

60.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [29]:
print(a)
print()
print(np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]))
print()
print(np.histogram(a, bins=[0, 50, 100]))

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]

(array([1, 0, 3, 1, 1, 1, 4, 2, 1, 1], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

(array([6, 9], dtype=int64), array([  0,  50, 100]))


### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [30]:
salary = np.array([20000, 40000, 50000, 30000, 25000])
experience = np.array([1, 2, 4, 3, 2])

print(np.corrcoef(salary, experience))

[[1.         0.80119274]
 [0.80119274 1.        ]]


### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [34]:
print(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


In [40]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

print(np.isin(a, items))
print()
print(a[np.isin(a, items)])

[False False False False  True False False False False False False False
 False False False]

[60]


### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [42]:
print(a)
np.flip(a)

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]


array([95, 25, 86, 64, 32, 67, 76, 54, 75, 24, 60, 26,  6, 67, 48])

In [45]:
print(b)
print()
print(np.flip(b))
# This performed flipping on column and on row

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]

[[47 61 48 90]
 [ 7 13 89  4]
 [41 89 33 21]
 [ 4 31 75 36]
 [ 8 36 98 14]
 [22 44 96 19]]


In [47]:
print(b)
print()
print(np.flip(b, axis=0))

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]

[[90 48 61 47]
 [ 4 89 13  7]
 [21 33 89 41]
 [36 75 31  4]
 [14 98 36  8]
 [19 96 44 22]]


In [48]:
print(b)
print()
print(np.flip(b, axis=1))

[[19 96 44 22]
 [14 98 36  8]
 [36 75 31  4]
 [21 33 89 41]
 [ 4 89 13  7]
 [90 48 61 47]]

[[22 44 96 19]
 [ 8 36 98 14]
 [ 4 31 75 36]
 [41 89 33 21]
 [ 7 13 89  4]
 [47 61 48 90]]


### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [50]:
print(a)
print()
# np.put(array, positions, values)

print(np.put(a, [0, 1], [110, 530]))
# NOTE - this makes a permanent change

[48 67  6 26 60 24 75 54 76 67 32 64 86 25 95]

None


In [51]:
print(a)

[110 530   6  26  60  24  75  54  76  67  32  64  86  25  95]


### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [54]:
print(a)
np.delete(a, 1)
# we give position like 1st index element

[110 530   6  26  60  24  75  54  76  67  32  64  86  25  95]


array([110,   6,  26,  60,  24,  75,  54,  76,  67,  32,  64,  86,  25,
        95])

In [56]:
print(a)
print(np.delete(a, [0, 2, 4]))

[110 530   6  26  60  24  75  54  76  67  32  64  86  25  95]
[530  26  24  75  54  76  67  32  64  86  25  95]


### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [67]:
# The best part is you get results in numpy array it self
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])
print("m: ", m)
print("n: ", n)

print("Union: ", np.union1d(m, n))
print("Intersect: ", np.intersect1d(m, n))
print("difference m - n: ", np.setdiff1d(m, n))
print("difference n - m: ", np.setdiff1d(n, m))
print("XOR: ", np.setxor1d(m, n))

m:  [1 2 3 4 5]
n:  [3 4 5 6 7]
Union:  [1 2 3 4 5 6 7]
Intersect:  [3 4 5]
difference m - n:  [1 2]
difference n - m:  [6 7]
XOR:  [1 2 6 7]


In [66]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])
print("m: ", m)
print("n: ", n)

# membership operator
print("", np.in1d(m, n))
m[np.in1d(m, n)]

m:  [1 2 3 4 5]
n:  [3 4 5 6 7]
 [False False  True  True  True]


array([3, 4, 5])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [70]:
# It restricts the numpy in a given range
# If they are below or above a certain range, it changes them to min and max mentioned respectively
print(a)
print()
np.clip(a, a_min=25, a_max=75)

[110 530   6  26  60  24  75  54  76  67  32  64  86  25  95]



array([75, 75, 25, 26, 60, 25, 75, 54, 75, 67, 32, 64, 75, 25, 75])

In [31]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [32]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [33]:

# 25. np.allclose and equals