**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [7]:
#Code here
a = np.nan * np.empty(10)
print(a)
a[4] = 1
print(a)

[nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan  1. nan nan nan nan nan]


### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
#Code here
input_a = int(input('Enter the a value: '))
input_b = int(input('Enter the b value: '))


def gen_random_array(a, b):
    rand_arr = np.random.random((a, b))
    print(rand_arr)
    print(np.average(rand_arr))
    print(np.mean(rand_arr))


gen_random_array(input_a, input_b)

[[0.60845262 0.11674283 0.83235733 0.57901849]
 [0.91407123 0.01372824 0.01479254 0.89666696]
 [0.73895293 0.44122009 0.53888417 0.07355345]]
0.4807034047891449
0.4807034047891449


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [17]:
#Code here

def border_arr(a, b):
    arr = np.ones((a, b))
    print(a, b)
    arr[1:-1, 1:-1] = 0
    return arr


print(border_arr(6, 10))

6 10
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [20]:
#Code here
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create an identity mattrix of shape (3,4). If yes write code for it.

In [23]:
#Code here
print(np.eye(3))
print()
print(np.identity(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [26]:
#Code here
z = np.zeros((5, 5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [39]:
#code here
a = np.random.randint(1, 100, (10, 2))
p = np.array([2, 3])
print(a, '\n\n', p, '\n')
# ((2 - 26) ** 2 + (3- 15) ** 2) ** 2
print(np.sqrt(np.sum((a - p) ** 2, axis=1)).astype(int))

[[43 56]
 [85  2]
 [17 19]
 [71  4]
 [ 8 20]
 [30  3]
 [32 76]
 [65 55]
 [ 7 69]
 [58 33]] 

 [2 3] 

[67 83 21 69 18 28 78 81 66 63]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
#Code here
a = np.random.random((6, 7, 8))
print(a)
b = np.unravel_index(100, (6, 7, 8))
print(b)
print(a[b])

[[[0.01385695 0.48870559 0.56057097 0.36662375 0.08254706 0.87180241
   0.80833777 0.9719533 ]
  [0.60635784 0.64779552 0.8381079  0.39554259 0.48673239 0.80076299
   0.90510035 0.1749873 ]
  [0.52121448 0.23317749 0.91005438 0.60100192 0.14690951 0.26053396
   0.90532663 0.88427807]
  [0.04685811 0.02431741 0.92666524 0.62641554 0.40958183 0.86008727
   0.35105245 0.1529148 ]
  [0.71859107 0.25267211 0.11049804 0.33754895 0.19452167 0.14767497
   0.4479199  0.12021781]
  [0.16460722 0.67942693 0.76602728 0.53232026 0.35933    0.57017127
   0.21233045 0.14332928]
  [0.87091951 0.27777056 0.86270021 0.9604547  0.95949454 0.30986804
   0.90090767 0.8126649 ]]

 [[0.39469605 0.04298594 0.1082991  0.251332   0.55071282 0.77605688
   0.98908159 0.37881283]
  [0.76581342 0.55206315 0.3716151  0.7236337  0.94059923 0.10387596
   0.4766877  0.32878472]
  [0.77331774 0.55714242 0.7275178  0.82275028 0.87187563 0.84444298
   0.2713832  0.97216278]
  [0.73687065 0.19897729 0.76634563 0.34349361 0

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [49]:
#Code here
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

array([9., 5., 3.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [50]:
#Code here
arr = np.array([])
arr2 = np.array([1, 2])
arr3 = np.array([[1, 2, 8], [5, 6, 8]])
print(arr.size, arr2.size, arr3.size)

0 2 6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [55]:
#Code here
input_1 = [86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]
input_2 = [33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278]


def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError('Requires Numpy Array')
    elif arr.ndim > 1:
        raise TypeError('Requires 1D Array')
    return np.exp(arr) / np.sum(np.exp(arr))


print(softmax(np.array(input_1)))
print(softmax(np.array(input_2)))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [60]:
#Coder here

def vert_stacking(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError('Requires numpy array')
    return np.vstack(args)
    # if type(arr1) != np.ndarray and type(arr2) != np.ndarray:
    #     raise TypeError('Requires numpy array')


a = np.arange(10).reshape(2, -1)
print(f"a: {a}\n")
b = np.repeat(1, 10).reshape(2, -1)
print(f"b: {b}\n")
print(vert_stacking(a, b))

a: [[0 1 2 3 4]
 [5 6 7 8 9]]

b: [[1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [61]:
c = np.random.random((2, 5))
print(f" c: {c} \n")
print(vert_stacking(c, c))

 c: [[0.75721703 0.75905301 0.08343573 0.60660945 0.30254892]
 [0.10170945 0.51010999 0.29681063 0.35158732 0.76238075]] 

[[0.75721703 0.75905301 0.08343573 0.60660945 0.30254892]
 [0.10170945 0.51010999 0.29681063 0.35158732 0.76238075]
 [0.75721703 0.75905301 0.08343573 0.60660945 0.30254892]
 [0.10170945 0.51010999 0.29681063 0.35158732 0.76238075]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [78]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError

    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04": 30, "05": 31, "06": 30, "07": 31, "08": 31, "09": 30,
                           "10": 31, "11": 30, "12": 31}

    # print(np.arange(start, end, dtype="datetime64[D]"))
    # Since we wanted to include the last end date as well, we need to make an increment at the end

    end = end.split("-")
    end_last = int(end[-1]) + 1

    # print(end)
    # print(end_last)

    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        # print(days_diff)
        end[-1] = f"0{days_diff}" if days_diff < 10 else f"{days_diff}"
        # print(end[-1])
        next_month = int(end[-2]) + 1
        # print(next_month)
        end[-2] = f"0{next_month}" if next_month < 10 else f"{next_month}"
        # print(end[-2])
    else:
        end[-1] = f"0{end_last}" if end_last < 10 else f"{end_last}"
    end = "-".join(end)

    return np.arange(start, end, dtype="datetime64[D]")


print(date_array(start='2020-09-15', end='2020-09-25'), '\n')
print(date_array(start='2020-11-01', end='2020-11-31'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25'] 

['2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04' '2020-11-05'
 '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09' '2020-11-10'
 '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14' '2020-11-15'
 '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19' '2020-11-20'
 '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24' '2020-11-25'
 '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29' '2020-11-30'
 '2020-12-01']


###`Q-14:` Subtract the mean of each row from a matrix.

In [101]:
#code here

ex = np.random.random((5, 4))
print(ex)
print()
print(ex.mean(axis=1, keepdims=True))
print()
print(ex - ex.mean(axis=1, keepdims=True))

[[0.35027474 0.40541883 0.9373559  0.12547021]
 [0.72826147 0.88410974 0.92787094 0.30469776]
 [0.52630917 0.58460092 0.26745172 0.68838883]
 [0.17132322 0.20100556 0.62655876 0.09877063]
 [0.44585413 0.12646938 0.59079127 0.67236703]]

[[0.45462992]
 [0.71123498]
 [0.51668766]
 [0.27441454]
 [0.45887045]]

[[-0.10435518 -0.04921109  0.48272598 -0.32915971]
 [ 0.01702649  0.17287476  0.21663597 -0.40653722]
 [ 0.00962151  0.06791326 -0.24923594  0.17170117]
 [-0.10309133 -0.07340898  0.35214422 -0.17564391]
 [-0.01301632 -0.33240107  0.13192082  0.21349657]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [106]:
#Code here
ex = np.arange(9).reshape(3, 3)
print(ex)
print()
print(ex[:, [0, 2, 1]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [107]:
ex = np.arange(12).reshape(3, 4)
print(ex)
print()
print(ex[:, [0, 2, 1, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [113]:
#Code here

a = np.arange(12)
print(a)
print(a % 2 == 1)
a[a % 2 == 1] = -1
print()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[False  True False  True False  True False  True False  True False  True]

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [118]:
#Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

a[b>a] = b[a<b] 
print(a)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [125]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)
print(arr1)
print()
print(arr1[:,::2])

[[3004 1439 4194 9741  776]
 [1927 3333 4407 8058  477]
 [7273 1799 6221 4524 3960]
 [1760 9520  328 8570 9569]
 [1689 3819 7680 9950 8415]
 [3496 8941 3977 1420 5317]
 [4758  489 4972 8062 1688]
 [8374 9928 2734 7440 9819]]

[[3004 4194  776]
 [1927 4407  477]
 [7273 6221 3960]
 [1760  328 9569]
 [1689 7680 8415]
 [3496 3977 5317]
 [4758 4972 1688]
 [8374 2734 9819]]


In [128]:
#Code here

def normalize(arr):
    return (arr - np.min(arr))/(np.max(arr) - np.min(arr))

print(normalize(arr1))

[[0.27811266 0.11546456 0.40178757 0.97827894 0.04655997]
 [0.16618167 0.31230513 0.42392434 0.80336728 0.01548535]
 [0.72178341 0.15287882 0.61245063 0.43608397 0.3774683 ]
 [0.14882561 0.95531075 0.         0.85657867 0.96040324]
 [0.14144668 0.36281438 0.76408231 1.         0.84046976]
 [0.32924548 0.89513615 0.37923509 0.11348992 0.51849927]
 [0.46040324 0.01673249 0.48264394 0.803783   0.14134276]
 [0.83620869 0.99771357 0.25005196 0.73913947 0.98638537]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [140]:
#Code here
def nth_largest(arr, n):
    if n > len(arr):
        raise IndexError('N is way out of limit')
    arr.sort()
    print(arr)
    print()
    return arr[-n]

a = np.random.randint(3, 100, 10)
print(a)
print()
nth_largest(a, 3)

[44 95 52 33 86 47 68 61 48 59]

[33 44 47 48 52 59 61 68 86 95]



68

In [132]:
np.random.randint(3, 100, 10)

array([69,  9, 55, 21, 48, 98, 10,  3, 54, 94])

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [144]:
#code her
a = np.array([1, 2, 3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])