## What is a Generator

Python generators are a simple way of creating iterators. 

In [ ]:
# iterable
class mera_range:

    def __init__(self, start, end):
        self.start = start
        self.end = end

    def __iter__(self):
        return mera_iterator(self)


# iterator
class mera_iterator:

    def __init__(self, iterable_obj):
        self.iterable = iterable_obj

    def __iter__(self):
        return self

    def __next__(self):
        if self.iterable.start >= self.iterable.end:
            raise StopIteration

        current = self.iterable.start
        self.iterable.start += 1
        return current

## The Why

In [3]:
import sys

x = range(100000)

# for i in x:
#     print(i**2)

print(sys.getsizeof(x) / 64, ' mb')

0.75  mb


## A Simple Example

In [12]:
# Generator does not have a return, it has yield

def gen_demo():
    yield 'First statement'
    yield 'Second statement'
    yield 'Third statement'

In [13]:
gen = gen_demo()
print(gen)

# On this gen, we can run next and get all the statements

<generator object gen_demo at 0x000002B3FD911380>


In [14]:
# print(next(gen))
# print(next(gen))
# print(next(gen))
# print(next(gen))

for i in gen:
    print(i)

First statement
Second statement
Third statement


## Python Tutor Demo (yield vs return)

## Example 2

In [17]:
def square(num):
    for i in range(1, num):
        yield i ** 2


gen = square(10)

print(next(gen))
print(next(gen))
print(next(gen))

for i in gen:
    print(i)

1
4
9
16
25
36
49
64
81


## Range Function using Generator

In [20]:
def mera_range(start, end):
    for i in range(start, end):
        yield i

In [21]:
for i in mera_range(15, 26):
    print(i)

15
16
17
18
19
20
21
22
23
24
25


## Generator Expression

In [23]:
L = [x ** 2 for x in range(1, 11)]
L

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [28]:
gen = (x ** 2 for x in range(1, 11))

for i in (x ** 2 for x in range(1, 11)):
    print(i)

1
4
9
16
25
36
49
64
81
100


## Practical Example

In [31]:
import os
import cv2


def image_data_reader(folder_path):
    for file in os.listdir(folder_path):
        f_array = cv2.imread(os.path.join(folder_path, file))
        yield f_array

In [34]:
gen = image_data_reader('C:\\Users\\15105\\Pictures\\Printing')
print(next(gen))
print(type(next(gen)))
print(next(gen).ndim)

[[[249 251 252]
  [249 251 252]
  [249 251 252]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[249 251 252]
  [249 251 252]
  [249 251 252]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[248 250 251]
  [248 250 251]
  [248 250 251]
  ...
  [246 246 246]
  [245 245 245]
  [245 245 245]]

 ...

 [[245 246 250]
  [245 246 250]
  [245 246 250]
  ...
  [248 247 249]
  [248 247 249]
  [249 246 248]]

 [[245 246 250]
  [245 246 250]
  [245 246 250]
  ...
  [248 247 249]
  [248 247 249]
  [249 246 248]]

 [[245 246 250]
  [245 246 250]
  [245 246 250]
  ...
  [248 247 249]
  [248 247 249]
  [249 246 248]]]
<class 'numpy.ndarray'>
3


## Benefits of using a Generator

#### 1. Ease of Implementation

#### 2. Memory Efficient

#### 3. Representing Infinite Streams

In [35]:
def all_even():
    n = 0
    while True:
        yield n
        n += 2

In [36]:
even_num_gen = all_even()
next(even_num_gen)
next(even_num_gen)

2

#### 4. Chaining Generators

In [37]:
def fibonacci_number(nums):
    x, y = 0, 1
    for _ in range(nums):
        x, y = y, x+y
        yield x

def square(nums):
    for num in nums:
        yield num ** 2

print(sum(square(fibonacci_number(10))))

4895
