In [1]:
import numpy as np

In [2]:
A = np.array([[1, 3, 4], [6, 4, 1], [2, 2, 2]])
B = np.array([5, 16, 4])

print(A)
print(B)

[[1 3 4]
 [6 4 1]
 [2 2 2]]
[ 5 16  4]


In [3]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[-0.75 , -0.25 ,  1.625],
       [ 1.25 ,  0.75 , -2.875],
       [-0.5  , -0.5  ,  1.75 ]])

In [4]:
np.dot(A_inverse, B)

array([-1.25,  6.75, -3.5 ])